//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cldv6212trialdb
{
    using Microsoft.AspNetCore.Http;
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; } 
        public string item_descr_and_name { get; set; }
        public string item_price { get; set; }
        public IFormFile item_image { get; set; }
        public string ImagePath { get; set; }
    }
}
